#spring.application.name=FoodAppMain
#
#
#spring.datasource.url = jdbc:mysql://localhost:3306/foodappmain
#spring.datasource.username = root
#spring.datasource.password = dexysexy@69
#
#spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
#
#spring.thymeleaf.cache = false
#
#server.port = 8080
# 

spring.application.name=FoodAppMain

#spring.datasource.url=jdbc:mysql://localhost:3306/foodappmain
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/foodappmain
spring.datasource.username=root
spring.datasource.password=dexysexy@69
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.thymeleaf.cache=false

server.port=8080